// <auto-generated />
namespace E_Auction.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class slsl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(slsl));
        
        string IMigrationMetadata.Id
        {
            get { return "201904171530106_slsl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
